# Generated by Django 2.0.1 on 2018-03-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20180315_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='recommender_by',
            new_name='recommended_by',
        ),
    ]
