# Generated by Django 2.0.1 on 2018-03-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('applicant', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[(0, 'admin'), (1, 'supervisor'), (2, 'recommender'), (3, 'approver'), (4, 'standard')], default=4, max_length=1)),
                ('designation', models.CharField(choices=[(0, 'Associate Professor'), (1, 'Assistant Professor'), (2, 'Professor'), (3, 'Other')], default=0, max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
