# Generated by Django 2.0.1 on 2018-03-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[(0, 'Associate Professor'), (1, 'Assistant Professor'), (2, 'Professor'), (3, 'Other')], default=3, max_length=1),
        ),
    ]
