# Generated by Django 2.0.1 on 2018-03-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180315_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'admin'), (1, 'supervisor'), (2, 'recommender'), (3, 'approver'), (4, 'standard')], default=4),
        ),
    ]
