# Generated by Django 2.0.1 on 2018-03-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180315_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
