# Generated by Django 2.0.1 on 2018-03-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180315_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Supervisor'), (2, 'Recommender'), (3, 'Approver'), (4, 'Standard')], default=4),
        ),
    ]
