# Generated by Django 2.0.3 on 2018-03-19 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reccomender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
