# Generated by Django 2.0.3 on 2018-03-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_reccomender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reccomender',
            new_name='recommender',
        ),
    ]
